spring: 
  application:
    name: libraryapi-production
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    url: jdbc:postgresql://localhost:5432/library
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
#     ddl-auto: update     
      ddl-auto: none
    properties:
      hibernate.format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID} 
            client-secret: ${GOOGLE_CLIENT_SECRET}

logging:
  file:
    name: app.log
  level:
    root: warn
    org:
      springframework:
        web: debug
        security: trace
# trace
# debug
# warn
# error

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: '*'
             
springdoc:
  override-with-generic-response: false